language: php

php:
  - 7.1.25

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - php artisan key:generate
  - php artisan migrate

script:
  - "./vendor/bin/phpunit" UserTest tests/Unit/UserTest.php 
